/**
 * FontAwesome Configuration - Tree-shaking optimized
 *
 * Only imports the icons actually used in the app
 * Reduces bundle size from ~90KB to ~15KB
 *
 * Note: Some Pro icons (fa-calendar-star) are used in CSS but not available
 * in the free version. They will render as empty icons until upgraded to Pro.
 */

import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

// Solid icons (fas) - Free version only
import {
  faArrowLeft,
  faArrowRight,
  faBan,
  faBolt,
  faCalendar,
  faCalendarAlt,
  faCalendarCheck,
  faCalendarDay,
  faCalendarPlus,
  faCalendarTimes,
  faCertificate,
  faChampagneGlasses,
  faChartArea,
  faChartBar,
  faChartLine,
  faChartPie,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircle,
  faCircleNotch,
  faClock,
  faCommentAlt,
  faCreditCard,
  faCrown,
  faDirections,
  faEnvelope,
  faEuroSign,
  faExclamationCircle,
  faExclamationTriangle,
  faExternalLinkAlt,
  faEye,
  faFilter,
  faFire,
  faGem,
  faGlassCheers,
  faHeart,
  faHome,
  faHourglassHalf,
  faInfoCircle,
  faLayerGroup,
  faLink,
  faLock,
  faMapMarkedAlt,
  faMapMarkerAlt,
  faMicrophone,
  faMinus,
  faMusic,
  faParking,
  faPause,
  faPercentage,
  faPlay,
  faPlus,
  faQrcode,
  faQuestion,
  faReceipt,
  faRedo,
  faSearch,
  faShieldAlt,
  faShoppingCart,
  faSignOutAlt,
  faSmoking,
  faSpinner,
  faStar,
  faSyncAlt,
  faTachometerAlt,
  faTicketAlt,
  faTimes,
  faTimesCircle,
  faTrophy,
  faTshirt,
  faUndo,
  faUser,
  faUserPlus,
  faUsers,
  faUsersSlash,
  faVideo,
  faWheelchair
} from '@fortawesome/free-solid-svg-icons'

// Brand icons (fab)
import {
  faFacebookF,
  faInstagram,
  faTwitter,
  faWhatsapp,
  faYoutube
} from '@fortawesome/free-brands-svg-icons'

// Add all icons to the library
library.add(
  // Solid
  faArrowLeft,
  faArrowRight,
  faBan,
  faBolt,
  faCalendar,
  faCalendarAlt,
  faCalendarCheck,
  faCalendarDay,
  faCalendarPlus,
  faCalendarTimes,
  faCertificate,
  faChampagneGlasses,
  faChartArea,
  faChartBar,
  faChartLine,
  faChartPie,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircle,
  faCircleNotch,
  faClock,
  faCommentAlt,
  faCreditCard,
  faCrown,
  faDirections,
  faEnvelope,
  faEuroSign,
  faExclamationCircle,
  faExclamationTriangle,
  faExternalLinkAlt,
  faEye,
  faFilter,
  faFire,
  faGem,
  faGlassCheers,
  faHeart,
  faHome,
  faHourglassHalf,
  faInfoCircle,
  faLayerGroup,
  faLink,
  faLock,
  faMapMarkedAlt,
  faMapMarkerAlt,
  faMicrophone,
  faMinus,
  faMusic,
  faParking,
  faPause,
  faPercentage,
  faPlay,
  faPlus,
  faQrcode,
  faQuestion,
  faReceipt,
  faRedo,
  faSearch,
  faShieldAlt,
  faShoppingCart,
  faSignOutAlt,
  faSmoking,
  faSpinner,
  faStar,
  faSyncAlt,
  faTachometerAlt,
  faTicketAlt,
  faTimes,
  faTimesCircle,
  faTrophy,
  faTshirt,
  faUndo,
  faUser,
  faUserPlus,
  faUsers,
  faUsersSlash,
  faVideo,
  faWheelchair,
  // Brands
  faFacebookF,
  faInstagram,
  faTwitter,
  faWhatsapp,
  faYoutube
)

export { FontAwesomeIcon }
